spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_study?allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: mycat123
  jpa:
    hibernate:
      ddl-auto: update   # 第一次建表用create,之后用update，
    show-sql: true    # 在控制台打印出sql语句
server:
  port: 8081
  servlet:
    context-path: /spring-boot-study
#logging:
#  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.study.spring.entity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
